# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  setup:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.9.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore npm dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          name: Cache npm dependencies
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  lint:
    working_directory: ~/repo

    docker:
      - image: circleci/node:12.9.1

    steps:
      - checkout

      - restore_cache:
          name: Restore npm dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # run tests!
      - run:
          name: Run lint
          command: yarn lint

  build:
    working_directory: ~/repo

    docker:
      - image: circleci/node:12.9.1

    steps:
      - checkout

      - restore_cache:
          name: Restore npm dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # run tests!
      - run:
          name: Run build
          command: yarn build

  test:
    working_directory: ~/repo

    docker:
      - image: circleci/node:12.9.1

    steps:
      - checkout

      - restore_cache:
          name: Restore npm dependencies
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # run tests!
      - run:
          name: Run test
          command: yarn test

workflows:
  version: 2
  setup_and_ci:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - setup
